### ISSUE TITLE
issue with the ceramic daemon --- ipfs-repo-migration does not have migration

### ISSUE THREAD

**Issue by bshambaugh** [spctcl/metasign#3]
ubuntu@brent-P65-67HSHP:~/Downloads/ethdenver2022$ nvm --version
0.34.0
ubuntu@brent-P65-67HSHP:~/Downloads/ethdenver2022$ ceramic daemon
Ceramic daemon failed to start up:
InvalidValueError: The ipfs-repo-migrations package does not have all migration to migrate from version 10 to 11
    at verifyAvailableMigrations (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-repo-migrations/src/index.js:270:11)
    at Object.revert (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-repo-migrations/src/index.js:185:3)
    at async IpfsRepo.open (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-repo/src/index.js:140:11)
    at async loadRepo (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-core/src/components/storage.js:74:5)
    at async Function.start (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-core/src/components/storage.js:54:41)
    at async Object.create (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/node_modules/ipfs-core/src/components/index.js:223:21)
    at async Function.create (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js:91:22)
    at async Object.buildIpfsConnection (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/lib/build-ipfs-connection.util.js:24:28)
    at async Function.create (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js:173:22)
    at async Command.<anonymous> (/home/ubuntu/.nvm/versions/node/v16.13.2/lib/node_modules/@ceramicnetwork/cli/lib/bin/ceramic.js:30:5) {
  code: 'ERR_INVALID_VALUE'
}
ubuntu@brent-P65-67HSHP:~/Downloads/ethdenver2022$ node --version
v16.13.2
ubuntu@brent-P65-67HSHP:~/Downloads/ethdenver2022$ npm --version
8.1.2

**Comment by bshambaugh** [comment]
Maybe I have some IPFS data files buried deep somewhere: https://github.com/ceramicnetwork/js-ceramic/issues/1742#issuecomment-1012562291

**Comment by bshambaugh** [comment]
I might need to delete the .jsipfs dot file:

ubuntu@brent-P65-67HSHP:~/.jsipfs$ ls -latr
total 48
-rw-rw-r--   1 ubuntu ubuntu   190 Feb  5  2021 datastore_spec
drwxrwxr-x   4 ubuntu ubuntu  4096 Feb  5  2021 keys
-rw-rw-r--   1 ubuntu ubuntu  3693 Apr 20  2021 config
drwxrwxr-x   2 ubuntu ubuntu  4096 Dec  8 14:02 local
-rw-rw-r--   1 ubuntu ubuntu     2 Dec  8 14:02 version
drwxrwxr-x 133 ubuntu ubuntu  4096 Dec  8 14:27 blocks
drwxr-xr-x   2 ubuntu ubuntu  4096 Jan 24 18:17 datastore
drwxr-xr-x   2 ubuntu ubuntu  4096 Jan 24 18:17 pins
drwxrwxr-x   7 ubuntu ubuntu  4096 Jan 24 18:17 .
drwxr-xr-x  95 ubuntu ubuntu 12288 Mar 18 13:05 ..

**Comment by bshambaugh** [comment]
Okay, that fixes it
